server:
  port: 8090
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "[ACCESS] %h %t \"%r\" %s %b"
      condition-unless: "NO_LOG"

masterello:
  user:
    email:
      enabled: true
      from: masterello1234@gmail.com
      registrationSubject: Please verify your registration
      resetPassSubject: Reset password email
      resetExpirationMinutes: 60
      serviceUrl: masterello.com
      sender: Masterello
      dailyAttempts: 3
  file:
    max-width: 4000
    max-height: 4000
    compressed-size: 1024
    bucket-name: 'masterello'
    cleanup-cron: "0 0 0 * * ?"
  auth:
    sessionCleanup:
      batchSize: 1000
      cron: "0 0 0 * * ?"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB