server:
  port: 8090
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "[ACCESS] %h %t \"%r\" %s %b"

masterello:
  user:
    email:
      enabled: true
      from: masterello1234@gmail.com
      subject: Please verify your registration
      sender: Masterello
  file:
    max-width: 4000
    max-height: 4000
    compressed-size: 1024
    bucket-name: 'masterello'

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB