spring:
  datasource:
    password: masterello
    username: masterello
    url: jdbc:postgresql://localhost:5432/masterello
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  application:
    name: masterello
  sql:
    init:
      mode: always
  mail:
    host: localhost
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: '25'
          starttls:
            enable: 'false'
            required: 'false'
          auth: 'false'
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 777134146814-n0jtdcbahc7ts5n2gfl5kvpdmf5tspd1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: https://masterello.com/{action}/oauth2/code/{registrationId}
            authorizationGrantType:
              - authorization_code
              - refresh_token
              - password
masterello:
  auth:
    token:
      access-token-ttl: 1h
      refresh-token-ttl: 1h
    google:
      verification-url: "https://oauth2.googleapis.com"
      success-redirect-url: "http://localhost/login/google"
  user:
    email:
      enabled: true
      from: masterello1234@gmail.com
      dailyAttempts: 100
  security:
    admin:
      username: admin@masterello.com
      password: 123qwe123
  file:
    spaces:
      accessKey: ${DO_SPACES_ACCESS_KEY}
      secretKey: ${DO_SPACES_SECRET_KEY}
      endpoint: ${DO_SPACES_ENDPOINT}
      region: ${DO_SPACES_REGION}
  openapi:
    oAuthFlow:
      tokenUrl: http:/127.0.0.1:8090/oauth2/token
  worker:
    ai:
      prompts:
        detect-language:
          id: pmpt_68692d13cf3481909d9f1c24b4b6cfe70a6dbf58e26ed355
        translate:
          id: pmpt_686936e1fdbc8197a5de3c2f260577b501d484eb5ae93302

logging:
  level:
    org.springframework.messaging.simp.broker.SimpleBrokerMessageHandler: DEBUG
    org.springframework.web.socket.messaging.SubProtocolWebSocketHandler: DEBUG
    org.springframework.messaging.simp: DEBUG

