spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 777134146814-n0jtdcbahc7ts5n2gfl5kvpdmf5tspd1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: https://masterello.com/{action}/oauth2/code/{registrationId}
            authorizationGrantType:
              - authorization_code
              - refresh_token
              - password
  datasource:
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: validate
  application:
    name: masterello-server
  sql:
    init:
      mode: always
  mail:
    host: email-smtp.eu-west-1.amazonaws.com
    username: ${SES_USERNAME}
    password: ${SES_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: '587'
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'

masterello:
  auth:
    token:
      access-token-ttl: 5m
      refresh-token-ttl: 1h
    google:
      verification-url: "https://oauth2.googleapis.com"
  user:
    email:
      enabled: false
      from: masterello1234@gmail.com
      subject: Please verify your registration
      sender: Masterello
  security:
    admin:
      username: admin@masterello.com
      password: ${SUPER_ADMIN_PASS}

management:
  health:
    mail:
      enabled: false