CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO category (uuid, name, original_name, description, category_code, parent_code, is_service, active)
VALUES
  (gen_random_uuid(), 'Home Repair and Construction', 'Home Repair and Construction', 'Description for Home Repair and Construction category', 1, NULL, false, true),
  (gen_random_uuid(), 'Apartment Renovation', 'Apartment Renovation', 'Description for Apartment Renovation category', 2, 1, true, true),
  (gen_random_uuid(), 'Electrical Installation', 'Electrical Installation', 'Description for Electrical Installation category', 3, 1, true, true),
  (gen_random_uuid(), 'Cleaning and Home Assistance', 'Cleaning and Home Assistance', 'Description for Cleaning and Home Assistance category', 4, NULL, false, true),
  (gen_random_uuid(), 'Apartment Cleaning', 'Apartment Cleaning', 'Description for Apartment Cleaning category', 5, 4, true, true),
  (gen_random_uuid(), 'Office Cleaning', 'Office Cleaning', 'Description for Office Cleaning category', 6, 4, true, true),
  (gen_random_uuid(), 'Transport and Moving', 'Transport and Moving', 'Description for Transport and Moving category', 7, NULL, false, true),
  (gen_random_uuid(), 'Cargo Transportation', 'Cargo Transportation', 'Description for Cargo Transportation category', 8, 7, true, true),
  (gen_random_uuid(), 'Loaders', 'Loaders', 'Description for Loaders category', 9, 7, true, true),
  (gen_random_uuid(), 'Tutoring and Education', 'Tutoring and Education', 'Description for Tutoring and Education category', 10, NULL, false, true),
  (gen_random_uuid(), 'Private Lessons', 'Private Lessons', 'Description for Private Lessons category', 11, 10, true, true),
  (gen_random_uuid(), 'Language Courses', 'Language Courses', 'Description for Language Courses category', 12, 10, true, true),
  (gen_random_uuid(), 'Computer Services', 'Computer Services', 'Description for Computer Services category', 13, NULL, false, true),
  (gen_random_uuid(), 'Computer Repair', 'Computer Repair', 'Description for Computer Repair category', 14, 13, true, true),
  (gen_random_uuid(), 'Software Development', 'Software Development', 'Description for Software Development category', 15, 13, true, true),
  (gen_random_uuid(), 'Graphic Design', 'Graphic Design', 'Description for Graphic Design category', 16, 13, true, true),
  (gen_random_uuid(), 'Event Organization', 'Event Organization', 'Description for Event Organization category', 17, NULL, false, true),
  (gen_random_uuid(), 'Birthday Parties', 'Birthday Parties', 'Description for Birthday Parties category', 18, 17, true, true),
  (gen_random_uuid(), 'Wedding Planning', 'Wedding Planning', 'Description for Wedding Planning category', 19, 17, true, true),
  (gen_random_uuid(), 'Photography', 'Photography', 'Description for Photography category', 20, NULL, false, true),
  (gen_random_uuid(), 'Portrait Photography', 'Portrait Photography', 'Description for Portrait Photography category', 21, 20, true, true),
  (gen_random_uuid(), 'Event Photography', 'Event Photography', 'Description for Event Photography category', 22, 20, true, true),
  (gen_random_uuid(), 'Health and Beauty', 'Health and Beauty', 'Description for Health and Beauty category', 23, NULL, false, true),
  (gen_random_uuid(), 'Haircuts and Styling', 'Haircuts and Styling', 'Description for Haircuts and Styling category', 24, 23, true, true),
  (gen_random_uuid(), 'Manicure and Pedicure', 'Manicure and Pedicure', 'Description for Manicure and Pedicure category', 25, 23, true, true),
  (gen_random_uuid(), 'Massage Therapy', 'Massage Therapy', 'Description for Massage Therapy category', 26, 23, true, true),
  (gen_random_uuid(), 'Fitness and Personal Training', 'Fitness and Personal Training', 'Description for Fitness and Personal Training category', 27, NULL, false, true),
  (gen_random_uuid(), 'Personal Trainer', 'Personal Trainer', 'Description for Personal Trainer category', 28, 27, true, true),
  (gen_random_uuid(), 'Yoga Classes', 'Yoga Classes', 'Description for Yoga Classes category', 29, 27, true, true),
  (gen_random_uuid(), 'Pet Services', 'Pet Services', 'Description for Pet Services category', 30, NULL, false, true),
  (gen_random_uuid(), 'Dog Walking', 'Dog Walking', 'Description for Dog Walking category', 31, 30, true, true),
  (gen_random_uuid(), 'Pet Sitting', 'Pet Sitting', 'Description for Pet Sitting category', 32, 30, true, true),
  (gen_random_uuid(), 'Gardening and Landscaping', 'Gardening and Landscaping', 'Description for Gardening and Landscaping category', 33, NULL, false, true),
  (gen_random_uuid(), 'Lawn Mowing', 'Lawn Mowing', 'Description for Lawn Mowing category', 34, 33, true, true),
  (gen_random_uuid(), 'Garden Design', 'Garden Design', 'Description for Garden Design category', 35, 33, true, true),
  (gen_random_uuid(), 'Legal Services', 'Legal Services', 'Description for Legal Services category', 36, NULL, false, true),
  (gen_random_uuid(), 'Legal Consultation', 'Legal Consultation', 'Description for Legal Consultation category', 37, 36, true, true),
  (gen_random_uuid(), 'Document Preparation', 'Document Preparation', 'Description for Document Preparation category', 38, 36, true, true),
  (gen_random_uuid(), 'Financial Services', 'Financial Services', 'Description for Financial Services category', 39, NULL, false, true),
  (gen_random_uuid(), 'Accounting Services', 'Accounting Services', 'Description for Accounting Services category', 40, 39, true, true),
  (gen_random_uuid(), 'Tax Consultation', 'Tax Consultation', 'Description for Tax Consultation category', 41, 39, true, true),
  (gen_random_uuid(), 'Business Consulting', 'Business Consulting', 'Description for Business Consulting category', 42, NULL, false, true),
  (gen_random_uuid(), 'Startup Consultation', 'Startup Consultation', 'Description for Startup Consultation category', 43, 42, true, true),
  (gen_random_uuid(), 'Marketing Services', 'Marketing Services', 'Description for Marketing Services category', 44, 42, true, true),
  (gen_random_uuid(), 'Arts and Crafts', 'Arts and Crafts', 'Description for Arts and Crafts category', 45, NULL, false, true),
  (gen_random_uuid(), 'Painting and Drawing', 'Painting and Drawing', 'Description for Painting and Drawing category', 46, 45, true, true),
  (gen_random_uuid(), 'Handmade Jewelry', 'Handmade Jewelry', 'Description for Handmade Jewelry category', 47, 45, true, true),
  (gen_random_uuid(), 'Music Lessons', 'Music Lessons', 'Description for Music Lessons category', 48, NULL, false, true),
  (gen_random_uuid(), 'Piano Lessons', 'Piano Lessons', 'Description for Piano Lessons category', 49, 48, true, true),
  (gen_random_uuid(), 'Guitar Lessons', 'Guitar Lessons', 'Description for Guitar Lessons category', 50, 48, true, true);

ALTER SEQUENCE category_code_seq RESTART WITH 51;


