name: 'Branch check workflow'
run-name: Branch ${{github.head_ref || github.ref_name}} by ${{github.actor}}

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'README.md'
      - 'local/**'
      - '.gitignore'
      - '.gitattributes'
      - '.github/**'


jobs:
  build-and-check:
    name: "Build and Check"
    uses: ./.github/workflows/reusable-check.yml
    secrets: inherit
  dependency-check:
    name: "OWASP check"
    uses: ./.github/workflows/owasp.yml
    secrets: inherit