name: Push to ECR

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: The branch, tag or SHA to checkout
      version:
        required: true
        type: string
        description: service version
    outputs:
      version:
        value: ${{ inputs.version }}

jobs:
  build-and-push-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push Docker Image
        env:
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          docker build -t registry.digitalocean.com/masterello-registery/server:$IMAGE_TAG -t registry.digitalocean.com/masterello-registery/server:latest  .
          docker push registry.digitalocean.com/masterello-registery/server:$IMAGE_TAG
          docker push registry.digitalocean.com/masterello-registery/server:$IMAGE_TAG