name: Push to ECR

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: The branch, tag or SHA to checkout
      version:
        required: true
        type: string
        description: service version
    outputs:
      version:
        value: ${{ inputs.version }}

jobs:
  build-and-push-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login -u masterello --password-stdin registry.digitalocean.com
      - name: Push Docker Image
        env:
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          docker push registry.digitalocean.com/masterello/server:$IMAGE_TAG